#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create:
  path: /create-article
  controller: App\Controller\ArticleController::createArticle

view:
  path: /view-article/{id}
  controller: App\Controller\ArticleController::viewArticle

show:
  path: /show-articles
  controller: App\Controller\ArticleController::showArticles

delete:
  path: /delete-article/{id}
  controller: App\Controller\ArticleController::deleteArticle

update:
  path: /update-article/{id}
  controller: App\Controller\ArticleController::updateArticle

cart_create:
  path: /create-cart/{id}
  controller: App\Controller\CartController::createCart

cart_show:
  path: /show-carts/
  controller: App\Controller\CartController::showCarts

cart_delete:
  path: /delete-cart/{id}
  controller: App\Controller\CartController::deleteCart